GITHUB_CLIENT_ID = 123
GITHUB_SECRET_ID = 123

GOOGLE_CLIENT_ID = 123
GOOGLE_SECRET_ID = 123

NEXTAUTH_URL = http://localhost:3000/
NEXTAUTH_SECRET = top_secret

DATABASE_URL = "123"

NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "123"

CLOUDINARY_API_KEY = 123
CLOUDINARY_SECRET_KEY = 123
CLOUDINARY_UPLOAD_PRESET = 123
